services:
  # Aplicación web personalizada - Instancia 1
  webapp1:
    build: .
    container_name: webapp_instance_1
    restart: always
    networks:
      - app_network

  # Aplicación web personalizada - Instancia 2
  webapp2:
    build: .
    container_name: webapp_instance_2
    restart: always
    networks:
      - app_network

  # Aplicación web personalizada - Instancia 3
  webapp3:
    build: .
    container_name: webapp_instance_3
    restart: always
    networks:
      - app_network

  # Nginx como Load Balancer
  nginx:
    image: nginx:alpine
    container_name: load_balancer
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webapp1
      - webapp2
      - webapp3
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
