global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Métricas de Prometheus mismo
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Métricas del sistema (Node Exporter)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  # Métricas de contenedores (cAdvisor)
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # Métricas de WordPress (si tuviera exportador)
  - job_name: "wordpress"
    static_configs:
      - targets: ["wordpress1:80", "wordpress2:80"]
    metrics_path: /wp-json/prometheus/metrics
    scrape_interval: 30s
    scrape_timeout: 10s
